### ISSUE TITLE
Bloodborne [CUSA00900] Vertex Explosions

### ISSUE THREAD

**Issue by IAmBatby** [shadps4-emu/shadPS4#1232]
Currently in Bloodborne there's a seemingly random chance for vertex explosions to occur. Based on my own testing and user reports I believe I have isolated the issue to files used in FACEGEN, A tool used to handle dynamic facial features used in FromSoft and Bethesda titles.

Explosions can occur on the player and any humanoid NPC. Explosions have been consistently prevented on the player by wearing helmet items that prevent the facegen meshes from loading

![image (5)](https://github.com/user-attachments/assets/bf0a88bd-2bb3-4c62-a49f-a0e6f2553762)
![image (6)](https://github.com/user-attachments/assets/957b16b1-e9fa-4429-a003-ad6ed42dbd86)
![IMG_8047](https://github.com/user-attachments/assets/ed580be3-d920-4489-bb67-c1e51db0f599)

relevant facegen files include

/dvdroot_ps4/facegen/facegen.fgbnd.dcx

/dvdroot_ps4/parts/fg_a_****.partsbnd.dcx

.dcx files are data containers FromSoft titles use. In particular FACEGEN's mesh data revolves around the following file formats

.flver
.tri
.egm

While briefly testing Dark Souls III I also had my characters face texture corrupt, which is a common issue for PC Bethesda games that is connected to corrupted FACEGEN data
![image](https://github.com/user-attachments/assets/a1d348e3-9d8b-4221-b94f-158f0b24b203)

I also found a mod for Fallout 4 that solves a similar vertex explosion that is tied to modifying FACEGEN data
https://www.nexusmods.com/fallout4london/mods/490

Some links to relevant FACEGEN documentation
https://facegen.com/dl/sdk/doc/manual/indepth.html
https://facegen.com/customizer_help.htm
https://facegen.com/dl/sdk/doc/manual/overview.html

**Comment by Hermiten** [comment]
This is a good issue, very complete but there is also some report about vertex things. I'm thinking about pairing up with the others

Thanks you

**Comment by IAmBatby** [comment]
Also worth mentioning that I while I have no data to back this up, the chances of this occurring significantly increase after dying, To the point where on my personal setup I'd guess a 80-90% success rate of re-producing via suicide

**Comment by IAmBatby** [comment]
> Also worth mentioning that I while I have no data to back this up, the chances of this occurring significantly increase after dying, To the point where on my personal setup I'd guess a 80-90% success rate of re-producing via suicide

To elaborate on this more I feel like these vertex explosions are tied to a race condition type situation. As far as I know almost every occurrence is from either loading a level directly (main menu, lamp, death) or walking into a zone that would trigger more stuff to be loaded

I think the reason why explosions seem to much more likely when the player dies is in relation to the fact the game should/ideally is loading a lot less because it can keep a lot of the current area loaded into memory which is not applicable in scenarios like loading from main menu or lamp transport 
Perhaps the facegen related meshes are a victim of said issue rather than the perpetrator

**Comment by abnerfreitas** [comment]
Im having the same issues. Its almost unplayable, have to go to main menu to reset constatly.

**Comment by REALCAZMANIAC** [comment]
I also have the same issue which is the only thing preventing me from playing through the game. But that doesn't mean this isn't a fantastic emulation of an exclusive ps4 title. Been wanting to play this again because i never beat it and love just playing.

**Comment by IAmBatby** [comment]
I have found that Fallout 3 via RPCS3 seems to be having a similar issue, With a correlation of FACEGEN usage and overall inconsistent framerate/frame pacing on a game heavily built for their target framerate.

https://github.com/RPCS3/rpcs3/issues/14862#issuecomment-2398349682

**Comment by IAmBatby** [comment]
Also likely unrelated but I found this issue and PR from kd-11 in regards to a Demon Souls explosion that was resolved by narrowing down potential race conditions when unprotecting memory which seems somewhat similar to some of the theories that have been floated around for this problem

https://github.com/RPCS3/rpcs3/pull/3858

**Comment by rainmakerv3** [comment]
I noticed when using the Vertex explosion mod (which removes facegen basically) that vertex explosions still happen, but they resolve themselves in succeeding frames in much the same way as a vertex explosion from certain race conditions. This can be observed in my gameplay video: https://www.youtube.com/watch?v=Lurb4eXEyBE&ab_channel=rainmakerv2 from 13:00 to 13:10.

This could perhaps mean that Facegen never really caused the vertex explosions, but instead somehow prevented them from being resolved like they normally are when caused by race.

If this is true, then I would suppose fixing the presumed race conditions during load would be the solution to this issue.

**Comment by rafael-57** [comment]
You can trigger this 100% reliably by:
Selecting new game -> Going into face details, and swapping between hair/beard options. It takes some moving in the menus but you will get it very fast.

I recommend it for any dev trying to debug this

**Comment by Hermiten** [comment]
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/1232

**Comment by 0pium001** [comment]
> I noticed when using the Vertex explosion mod (which removes facegen basically) that vertex explosions still happen, but they resolve themselves in succeeding frames in much the same way as a vertex explosion from certain race conditions. This can be observed in my gameplay video: https://www.youtube.com/watch?v=Lurb4eXEyBE&ab_channel=rainmakerv2 from 13:00 to 13:10.
> 
> This could perhaps mean that Facegen never really caused the vertex explosions, but instead somehow prevented them from being resolved like they normally are when caused by race.
> 
> If this is true, then I would suppose fixing the presumed race conditions during load would be the solution to this issue.

can i get the link for the mod

**Comment by rainmakerv3** [comment]
its against the rules on discord to link to game mods, so I assume the same is true here. But you can search vertex explosion fix on nexus mods to find it

**Comment by Hermiten** [comment]
This one still occur, I open it again

**Comment by sam20112011** [comment]
Readbacks WIP https://github.com/shadps4-emu/shadPS4/pull/2668

**Comment by emoose** [comment]
Enabling readbacks seems to halve FPS for me, but I noticed removing/commenting these UpdateProtection lines seems to give performance back without any vertex explosions happening (at least I didn't see any in an hour of play, game run at full 60FPS with the readbacks option enabled)

https://github.com/shadps4-emu/shadPS4/blob/42e3ce9465c4fe2398cde2c77a78f7e3d4eda452/src/video_core/buffer_cache/region_manager.h#L98-L100

https://github.com/shadps4-emu/shadPS4/blob/42e3ce9465c4fe2398cde2c77a78f7e3d4eda452/src/video_core/buffer_cache/region_manager.h#L129-L132

Guess this is probably breaking something though but maybe still interesting, this is just leaving the single Config::readbacks() check inside memory_tracker.h:

https://github.com/shadps4-emu/shadPS4/blob/42e3ce9465c4fe2398cde2c77a78f7e3d4eda452/src/video_core/buffer_cache/memory_tracker.h#L68-L78

Wonder why just leaving that part is still fixing them.

E: ah apparently this is what some forks already added, should have checked first - hope a real fix for them can be found.

**Comment by StevenMiller123** [comment]
Readbacks is known to fix the vertex explosions described here. This issue is still open because our readbacks implementation is imperfect, and regresses some games (on top of the performance issues). Once readbacks are stable and fast enough to enable by default, this issue will be closed.

**Comment by StevenMiller123** [comment]
Closing as completed since the readbacks setting is known to fix the issues described here.
