### ISSUE TITLE
VK 1.3 is required

### ISSUE THREAD

**Issue by EmuAl** [shadps4-emu/shadPS4#232]
I have a AMD RX 6900XT GPU and the games i try crash with the following error:

[Debug] <Critical> vk_instance.cpp:operator():80: Assertion Failed!
Vulkan 1.3 is required, but only 1.2 is supported by device

any idea if this is fixable please

thanks

**Comment by raphaelthegreat** [comment]
You need to update your drivers

**Comment by EmuAl** [comment]
thanks but i am on latest amd gpu driver 24.6.1 ?

**Comment by raphaelthegreat** [comment]
Then your GPU should definitely support 1.3

**Comment by EmuAl** [comment]
![2024-07-02](https://github.com/shadps4-emu/shadPS4/assets/47227078/8fecfef1-d039-4a04-913c-83d29c21813b)
is this enough to use the emulator ?

**Comment by raphaelthegreat** [comment]
Looks fine to me

**Comment by EmuAl** [comment]
so must be a bug then ?

**Comment by raphaelthegreat** [comment]
Hm probably. Try installing latest Vulkan SDK

**Comment by EmuAl** [comment]
will do, thanks

**Comment by EmuAl** [comment]
[Debug] <Critical> vk_instance.cpp:operator():80: Assertion Failed!
Vulkan 1.3 is required, but only 1.2 is supported by device!

same error after installation of VulkanSDK-1.3.283.0
hopefully it can fixed, will keep trying new versions as and when released

**Comment by l33tm4st3r** [comment]
Hi all.

 Just remove "OpenCL™, OpenGL®, and Vulkan® Compatibility Pack" package from windows installed apps.

Have a nice day.

**Comment by EmuAl** [comment]
Sorry but this isn't installed on my pc

**Comment by RainKikyou** [comment]
I have the same with problem
![QQ截图20240705235727](https://github.com/shadps4-emu/shadPS4/assets/20301499/88183a2b-50d7-4301-8da6-d8f7b54548ae)
![image](https://github.com/shadps4-emu/shadPS4/assets/20301499/31c2a6f5-8837-45d0-827b-cb76e8f370ba)
![image](https://github.com/shadps4-emu/shadPS4/assets/20301499/de4878e6-1afc-41d9-8471-7949774d722e)
![QQ图片20240706124712](https://github.com/shadps4-emu/shadPS4/assets/20301499/3c0b9cbd-e46c-4aea-8c28-66f0634e2b51)

My PC
Processor: Intel 13th Generation Core i7-13700H 14-core 
Motherboard:ASUS FX507VV
Memory:48GB DDR5 5200MHz (24GB + 24GB)
Graphics:Intel(R) Iris(R)Xe Graphics (128MB/ASUS) NVIDIA GeForce RTX 4060 Laptop GPU (8GB/ASUS)
Monitor: PG27UQR[ASUS AUS274B] (27.2 inches) NE156FHM-NX6[BOE BOEOB70] (15.3 inches)
Disk:KIOXIA TransMemory USB Device (62GB) NVMe WD Blue SN580 2TB (2000GB) NVMe WD PC SN740 SDDPNQD-512G-1002 (512GB)
Sound card:Realtek High Definition AudioUSB Audio Device NVIDIA High Definition Audio
Network card:Realtek PCle GbE Family ControllerIntel(R) Wi-Fi 6 AX201 160MHz Realtek 8811CU Wireless LAN 802.11ac USB NIC

Finally，I solved this problem（This solution may only be suitable for laptops）
This solution may only be suitable for laptops. You need to change the 1 of gpuId to 0. 0 is the independent graphics card and 1 is the integrated graphics card.
![QQ截图20240706201040](https://github.com/shadps4-emu/shadPS4/assets/20301499/71e478fd-446b-45c2-b343-7855b4ed3fe9)
![QQ图片20240706201238](https://github.com/shadps4-emu/shadPS4/assets/20301499/33965feb-af57-49a8-9e87-711e5eba2335)

**Comment by dsyo2008** [comment]
Same problem

**Comment by Danik2343** [comment]
Same problem, solved with gpuid 0

**Comment by EmuAl** [comment]
> Same problem, solved with gpuid 0

Can you explain this please, thanks 🙏

**Comment by EmuAl** [comment]
so i figured it out myself, in the user folder, open the config.toml and under the [GPU] heading, set gpuId = 0
the games don't crash with this error now

**Comment by V6ser** [comment]
> so i figured it out myself, in the user folder, open the config.toml and under the [GPU] heading, set gpuId = 0 the games don't crash with this error now

Did you edit config.toml before or does it still happen if you try a clean build? If it still does, then it's likely better not to close this issue.

**Comment by EmuAl** [comment]
yes it still happens on current version on fresh extraction

**Comment by SamuelFontes** [comment]
There was a change that should have solved this issue, but the TargetVulkanApiVersion is being set as VK_API_VERSION_1_2
https://github.com/shadps4-emu/shadPS4/blob/ab56665d4b75e13e99e824dc531b8642d0377632/src/video_core/renderer_vulkan/vk_platform.h#L20
https://github.com/shadps4-emu/shadPS4/blob/ab56665d4b75e13e99e824dc531b8642d0377632/src/video_core/renderer_vulkan/vk_instance.cpp#L72-L78
So in these cases it's selecting the wrong gpu, is there any reason why this is not set as VK_API_VERSION_1_3 since it's required?

**Comment by SamuelFontes** [comment]
@EmuAl could you try this run to see if the issue was solved?
https://github.com/shadps4-emu/shadPS4/actions/runs/10323398795

**Comment by EmuAl** [comment]
it doesn't crash with the same error but does just sit on black screen
the gpuid=-1 is in the config.toml but it still needs gpuId = 0 to run games

**Comment by SamuelFontes** [comment]
I've create a pull request that should solve this issue, giving the possiblity of choosing the GPU from the graphical interface. https://github.com/shadps4-emu/shadPS4/pull/399

![image](https://github.com/user-attachments/assets/0c04539c-afe1-43d4-8a36-b30d04631451)
If the GPU doesn't support the target vulkan API version this is how it will be shown.
![image](https://github.com/user-attachments/assets/de562c11-bc60-4568-b4b3-b0c7a12ce6f6)

**Comment by SamuelFontes** [comment]
The change got merged, please validate if the issue was solved.

**Comment by EmuAl** [comment]
so with a clean extract, the auto select option doesn't pick my gpu as i still get the black screen when trying to run a game, 
if i pick my gpu in the drop down then the games work

**Comment by SamuelFontes** [comment]
So choosing the right GPU solves the problem, now it's easier to know what GPU is the correct one instead of trying to blindly change the gpuId in the config files.
But just out of curisity, can you attach a screenshot with all the options on the dropdown?
I'm wondering why the auto selection is choosing the wrong GPU.

**Comment by EmuAl** [comment]
![2024-08-15 (2)](https://github.com/user-attachments/assets/f8d26843-a9bf-49ef-a77c-1e72893bcf13)

**Comment by V6ser** [comment]
> ![2024-08-15 (2)](https://private-user-images.githubusercontent.com/47227078/358326136-f8d26843-a9bf-49ef-a77c-1e72893bcf13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjQ1OTEsIm5iZiI6MTcyMzk2NDI5MSwicGF0aCI6Ii80NzIyNzA3OC8zNTgzMjYxMzYtZjhkMjY4NDMtYTliZi00OWVmLWE3N2MtMWU3Mjg5M2JjZjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA2NTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZjA3ZjMxZDVlYmZhYzZhMmFjZDU0MDc0ZDliNDRkNTdhOWIxOGNjNzAxNjliOWVmZTdiNzVjYmFlNDlkZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bOjDr3GPSMYKmkbPp3flZGRjYFapCmlinSxWU49VM-M)

This look like driver issues on your end tbh

**Comment by EmuAl** [comment]
> This look like driver issues on your end tbh

in what way ?

the driver is fully updated, there's not much else i can do to it

**Comment by V6ser** [comment]
> > This look like driver issues on your end tbh
> 
> in what way ?
> 
> the driver is fully updated, there's not much else i can do to it

There are 2 GPUs shown in your shadps4's list. One of them has Basic Display Adapter driver from Microsoft. And your discrete GPU is not recognized through its Vulkan version. From those two, I'm just guessing, but looks like driver issues.

**Comment by Hermiten** [comment]
I think this can be close, you can noy choose the right gpu.

**Comment by EmuAl** [comment]
Yep can be as it’s possible to do from settings but on first extract it still happens, but as people have said above it could be driver related. Will close now.
