### ISSUE TITLE
[APP BUG]: Translated Log type written to config

### ISSUE THREAD

**Issue by f1amy** [shadps4-emu/shadPS4#2356]
### Checklist

- [x] I have searched for a similar issue in this repository and did not find one.
- [x] I am using an official build obtained from [releases](https://github.com/shadps4-emu/shadPS4/releases) or updated one of those builds using its in-app updater.

### Describe the Bug

In the settings UI, Debug -> Logger -> Log Type we recently got translations for items "async" and "sync"
So it no longer works and "async" is always assumed

However it seems to save translated value to config, even though it was available for translation

See how it is saved:
https://github.com/shadps4-emu/shadPS4/blob/f5d64239cbc5afa89addc0caa281a50558661865/src/qt_gui/settings_dialog.cpp#L358

UI file:
https://github.com/shadps4-emu/shadPS4/blob/f5d64239cbc5afa89addc0caa281a50558661865/src/qt_gui/settings_dialog.ui#L1791

Solutions:
1. Make it so on save it checks for index of a value or add as display text
or
2. Disable translations for these values

### Reproduction Steps

1. Use latest Nightly build
2. Set emulator language to Ukranian or Russian
3. Select a Log type
4. Save settings

### Expected Behavior

"sync" or "async" is written to config

### Specify OS Version

Windows 11

**Comment by f1amy** [comment]
cc @DanielSvoboda

**Comment by f1amy** [comment]
сс @GHU7924

**Comment by GHU7924** [comment]
You can see these points in this comment - https://github.com/shadps4-emu/shadPS4/pull/2318#issuecomment-2633680243 
In the video: Без полей = Borderless

**Comment by Hermiten** [comment]
I can reproduce it easely on the last nightly, it save the word "sync" or "async" in russian so this is not used anymore by the game.
Someone available to fix it ?

**Comment by Hermiten** [comment]
@DanielSvoboda Sorry to ping you again, but do you know if it's fixed ?

**Comment by DanielSvoboda** [comment]
> [@DanielSvoboda](https://github.com/DanielSvoboda) Sorry to ping you again, but do you know if it's fixed ?

I don't think it has been resolved, and the same problem should affect the 'full screen' option, I'm finishing configuring Crowdin, then I'll resolve these other problems involving language.
What should happen is to get the information based on the selected index and not according to the text

**Comment by Hermiten** [comment]
Can you test again ? Somes fixes have been pushed

**Comment by GHU7924** [comment]
@Hermiten @DanielSvoboda As for writing the type of log, it is now written in English. Fixed.
As for the other problem, it still exists. But I noticed an important thing: along with the type of screen, the type of magazine also changes when switching the language. At least I saw this when switching between English and Russian, and it may be present in other translations if these points are translated. I do not know if it has affected anything else, but so far I have noticed only these 2 changes.

I repeat the essence of the problem: if you have the screen type "True" and the log type "async", then after switching to another emulator language, these two parameters will be reset to "Borderless" and "sync", respectively.

I don't know if it makes sense to close this issue and open a new one, or fix everything in this one so as not to create a new one.

**Comment by DanielSvoboda** [comment]
I recently made changes so that the interface is translated, but what is written in the settings/log is in English. But I couldn't repeat what you said, could you write a step by step? I change the options, I change the language, but the choices I left remain. The only one that is reset is this one, but I don't see a problem in this case.
![Image](https://github.com/user-attachments/assets/4a5570e4-2ec3-439b-b5c7-78b99edfc8df)

**Comment by GHU7924** [comment]
@DanielSvoboda 
Fullscreen Mode:
Истинный = True
Без полей = Borderless

Log Type:
асинхронный = async
синхронный = sync

English to Russia

https://github.com/user-attachments/assets/d7bd5373-b2ba-4794-a507-3b4547a43ad7

Russia to English

https://github.com/user-attachments/assets/678ae1d8-a4b8-40ce-b6c8-07eec4395809

**Comment by DanielSvoboda** [comment]
Thanks for the video, it seems to me to be a problem specific to the Russian language, maybe it's because of the different characters. Because when I change from English to Portuguese and vice versa it works correctly. It must be a problem reading the Russian character

**Comment by GHU7924** [comment]
I have not seen before that there is also a default tab reset. After you, I checked and I can confirm that this is indeed happening. Then it turns out that the reset occurs for 3 elements. They need to be fixed.

>Thanks for the video, it seems to me to be a problem specific to the Russian language, maybe it's because of the different characters. Because when I change from English to Portuguese and vice versa it works correctly. It must be a problem reading the Russian character

When these items were not translated, they worked correctly. After they were transferred, a reset began to occur.
So you think the problem is that the emulator doesn't understand (or can't read) Cyrillic? Maybe it is. There are no problems with the Latin alphabet.

**Comment by DanielSvoboda** [comment]
test this, it should solve it
I didn't make the correction for the 'tab' selection, I don't think it's necessary...
https://github.com/shadps4-emu/shadPS4/actions/runs/13333382857

**Comment by GHU7924** [comment]
@DanielSvoboda I can check it out later.

>I didn't make the correction for the 'tab' selection, I don't think it's necessary...

I think it's still worth fixing, because we know about the problem. This will also preclude re-patching in the future if someone encounters this issue. If everything is working correctly, then you won't have to fix it))

In addition, if someone undertakes the implementation of issue 2418, it is also important that there is no reset of the choice.

**Comment by DanielSvoboda** [comment]
added the fix for tab/chooseHomeTab
https://github.com/shadps4-emu/shadPS4/actions/runs/13334453247

**Comment by GHU7924** [comment]
@Hermiten You can close it. Fixed in 2433.

**Comment by Hermiten** [comment]
When it will be merged

**Comment by f1amy** [comment]
Fixed in #2433. Thanks!
