### ISSUE TITLE
[GAME BUG]: Save issues in several games

### ISSUE THREAD

**Issue by StevenMiller123** [shadps4-emu/shadPS4#2733]
### Checklist (we expect you to perform these steps before opening the issue)

- [x] I have searched for a similar issue in this repository and did not find one.
- [x] I am using an official build obtained from [releases](https://github.com/shadps4-emu/shadPS4/releases) or updated one of those builds using its in-app updater.
- [x] I have re-dumped the game and performed a clean install without mods and the issue is still present.
- [x] I have disabled all patches and cheats and the issue is still present.
- [x] I have all the required [system modules](https://github.com/shadps4-emu/shadps4-game-compatibility?tab=readme-ov-file#informations) installed.

### Describe the Bug

This occurs in the following titles:
- ~J-STARS Victory VS+ (CUSA01593)~ Fixed #2851 
- ~DRAGON BALL XENOVERSE (CUSA01341)~ Fixed #3099 
- ~DRAGON BALL XENOVERSE 2 (CUSA05350)~ Fixed #3099 

I'm creating this issue at the request of @viniciuslrangel
All tests were performed on the latest pre-release as-of the creation of this issue.

### Specify OS Version

Windows 11 23H2

### CPU

12th Gen Intel(R) Core(TM) i7-1280P

### GPU

Intel(R) Iris(R) Xe Graphics

### Amount of RAM in GB

32 GB

### Amount of VRAM in GB

16 GB

**Comment by Missake212** [comment]
I've been told by Stephen that Catherine Full Body crashes due to save issues so here's a log.

[CUSA15036.log](https://github.com/user-attachments/files/19858379/CUSA15036.log)

**Comment by viniciuslrangel** [comment]
@Missake212 @StevenMiller123 Give a try with this #2851

**Comment by StevenMiller123** [comment]
@viniciuslrangel That doesn't seem to fix any of the save issues in the DRAGON BALL XENOVERSE titles. I'm still working on testing J-STARS.

[DBXV save create.txt](https://github.com/user-attachments/files/19930630/DBXV.save.create.txt)
[DBXV save load failed.txt](https://github.com/user-attachments/files/19930631/DBXV.save.load.failed.txt)
[DBXV2 save create.txt](https://github.com/user-attachments/files/19930628/DBXV2.save.create.txt)
[DBXV2 save load failed.txt](https://github.com/user-attachments/files/19930629/DBXV2.save.load.failed.txt)

**Comment by StevenMiller123** [comment]
J-STARS Victory Vs+ appears to be fixed. I'm able to create, view, and delete replay data successfully.

[shad_log.txt](https://github.com/user-attachments/files/19930674/shad_log.txt)

**Comment by StevenMiller123** [comment]
Most of the issues in here are still valid, reopening.

**Comment by StevenMiller123** [comment]
I've run out of save issues to report here.
@Missake212 Feel free to post your newer save issues here for easier tracking.

**Comment by Missake212** [comment]
Found another save issue thanks to a comment on one of my reports on the compatibility list, 13 Sentinels Aegis Rim saves work, but you can't have multiple saves at the same time for some reason, once you quit the game they all disappear beside the last one , first screenshot is me saving the game, second screenshot is after closing it and launching it again. 

![Image](https://github.com/user-attachments/assets/0c57888b-4f1b-441f-9e53-689ac35cc20d)
![Image](https://github.com/user-attachments/assets/72438b68-5466-4e80-83aa-fc910e392b05)

It seems to be an issue only upon relaunching the game, when you make multiple saves you can load them all without issues, but quit the game and come back and all but one are gone, I've tried looking at the size of the file during the whole process but it didn't change, I also tried making a copy of the folder right after saving while the game is still on then quitting the game and replacing the save file with the copy but it didn't work, so not sure what the issue is really.

[CUSA19620.log](https://github.com/user-attachments/files/20747445/CUSA19620.log)

@UltraDaCat can you post about the save issue in Catherine Full Body?

**Comment by UltraDaCat** [comment]
It seems that Catherine Full Body suffers from a saving issue, as loading PS4 saves works just fine(as shown in the 1st and 2nd image attached to this comment). However, saving the game on the emulator causes the saves not to appear when attempting to load the game, even when saving to another slot(as shown in the 3rd and 4th image).

![Image](https://github.com/user-attachments/assets/9d61a239-361e-457a-8dc3-c8012da7e327)

![Image](https://github.com/user-attachments/assets/78a051ed-2746-45f9-8ad6-dd97dfc1870a)

![Image](https://github.com/user-attachments/assets/7fc3fd8d-e0dc-4e96-bcc1-4c5399efce77)

![Image](https://github.com/user-attachments/assets/652d15f1-489a-486a-8de3-36488e757da7)

**Comment by StevenMiller123** [comment]
@UltraDaCat Please provide a log with the log filter set to `Lib.SaveData:Debug Lib.SaveDataDialog:Debug`

**Comment by UltraDaCat** [comment]
Here you go
[shad_log.txt](https://github.com/user-attachments/files/20747688/shad_log.txt)

**Comment by Missake212** [comment]
Gran Turismo Sport (CUSA02168) version 1.00 fails to create a save file (but version 1.69 creates one with no problem), it creates the sce_sdmemory folder but not the local-data one. Here are both save files so you can compare them better @viniciuslrangel 

[sce_sdmemory 1.00.zip](https://github.com/user-attachments/files/21093427/sce_sdmemory.1.00.zip)

[sce_sdmemory 1.69.zip](https://github.com/user-attachments/files/21093428/sce_sdmemory.1.69.zip)

And a log: 

[CUSA02168.log](https://github.com/user-attachments/files/21093466/CUSA02168.log)

And a stack trace too:

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/d8de6023-e1c8-4b68-b3c6-efa63c8059d5" />

**Comment by W1nd0wZz** [comment]
@UltraDaCat has this issue been resolved in catherine FB yet? ive been tryin my best to play the game despite its save issue, not fun

**Comment by StevenMiller123** [comment]
Catherine Full Body save issues are not fixed yet.
A fix was published a while back, but it hasn't been merged yet.

If you want to play the game, I suggest sticking to real hardware for now.

**Comment by W1nd0wZz** [comment]
thats a shame, thanks tho

**Comment by StevenMiller123** [comment]
Everything in here is fixed, so I'm closing this.
Future save issues can warrant a new issue.

**Comment by StevenMiller123** [comment]
Acutally, is the GT Sport issue solved?
