### ISSUE TITLE
ShadSP4 doesn't launch Bloodborne on my system unless failed assertions & unreachable code are commented out

### ISSUE THREAD

**Issue by 0xBA5E64** [shadps4-emu/shadPS4#285]
When trying to boot Bloodborne (`CUSA03173` App ver. 6) in ShadPS4 on my system built from the latest commit (https://github.com/shadps4-emu/shadPS4/commit/f3baad7fc87bd4bf8840a4d1f50d30151b9c5580), shadPS4 yields with errors like this:
```
[Debug] <Critical> tls.cpp:operator():122: Assertion Failed!
```
-on the following three lines:
https://github.com/shadps4-emu/shadPS4/blob/f3baad7fc87bd4bf8840a4d1f50d30151b9c5580/src/core/tls.cpp#L122
https://github.com/shadps4-emu/shadPS4/blob/f3baad7fc87bd4bf8840a4d1f50d30151b9c5580/src/video_core/amdgpu/resource.h#L69
https://github.com/shadps4-emu/shadPS4/blob/f3baad7fc87bd4bf8840a4d1f50d30151b9c5580/src/video_core/texture_cache/texture_cache.cpp#L43

Recompiling shadPS4 with these three lines commented out gets Bloodborne into menus, just as previously documented in George Moralis's latest [showcase](https://youtu.be/zoMO4N92Vss):
![Screenshot_20240711_164848](https://github.com/shadps4-emu/shadPS4/assets/26796481/4bb5a908-c40e-4525-97d7-3c50c2382054)

## System Info
- **OS:** Arch Linux (Linux 6.9.8-arch1-1)
- **CPU:** AMD Ryzen 9 7950X3D
- **GPU:** AMD Radeon RX 7900 XTX
- **RAM:** 64GB DDR5

**Comment by georgemoralis** [comment]
we are aware of this , it's some bugz that need to be fixed that's why 0.1.1 is stil WIP :D

**Comment by raphaelthegreat** [comment]
The first error is some condition hit by certain linux distros regarding TLS. The second is the main assert that blocks the boot on most systems and is related to unimplemented buffer format conversions. The final one haven't seen though, might be caused by your debugger

**Comment by 0xBA5E64** [comment]
> The final one haven't seen though

Interesting... I suppose I'll have to look more into why that one in particular is happening.

> might be caused by your debugger

I'm simply building with `cmake --build . --parallel$(nproc)`, as per the Linux building instructions, no debugger afaik:

https://github.com/shadps4-emu/shadPS4/blob/f3baad7fc87bd4bf8840a4d1f50d30151b9c5580/documents/building-linux.md?plain=1#L47-L50

**Comment by 0xBA5E64** [comment]
**UPDATE:** https://github.com/shadps4-emu/shadPS4/pull/293 fixed the first two issues for me, leaving me with just the third, supposedly 'unique' error;
```
[Debug] <Critical> texture_cache.cpp:GuestFaultSignalHandler:43: Unreachable code!
```

Full log: [`CUSA03173.log`](https://github.com/user-attachments/files/16238525/CUSA03173.log)

Interestingly, commenting out said line from the source now no longer seems to let the game to boot anymore...

**Comment by raphaelthegreat** [comment]
The PR you linked also removed a hack I added for BB to boot on linux. You can find the commit and reapply it if you want to test it locally. But it breaks a bunch of other games so I need to implement that properly

**Comment by VasylBaran** [comment]
@0xBA5E64 completely unrelated, but what tool do you use to show these on-screen performance metrics on Linux? Thank you! ;-)

**Comment by 0xBA5E64** [comment]
@VasylBaran That right there is [MangoHud](https://github.com/flightlessmango/MangoHud). You can either run it as a wrapper for most OpenGL/Vulkan Programs or configure it to run globally on your system, at which point it'll automatically hook into any such app you open through an environment variable.

**Comment by gelson-zord** [comment]
On my PC (Win11-3700X-3080Ti) Bloodborne serial `CUSA00900` crash on booting in WIP 0.1.1. Maybe it's the same cause.
[shad_log.txt](https://github.com/user-attachments/files/16258672/shad_log.txt)

**Comment by huntyboy102** [comment]
@gelson-zord I had the same issue with `CUSA00900` when I was building with VS Code. Try building in QT. Not sure why this works but it seemed to have helped me.

**Comment by gelson-zord** [comment]
@huntyboy102 I didn't build it, I just got the last build from Actions here. Could you share yours?

**Comment by huntyboy102** [comment]
@gelson-zord certainly. If you're in the discord just PM or ping me and I'll send something when I building their changes tonight.

**Comment by rafael-57** [comment]
shouldn't this be closed as fixed by now? The game boots

**Comment by Hermiten** [comment]
Same question than @rafael-57

**Comment by 0xBA5E64** [comment]
This issue should indeed probably be closed. Although the game still doesn't boot on my system, the issues listed originally are no longer relevant.
