### ISSUE TITLE
[GAME BUG]: CUSA03745 Trico/Can't climb/invisible spear/doesn't consume barrels?

### ISSUE THREAD

**Issue by DosDokTor** [shadps4-emu/shadPS4#2861]
### Checklist (we expect you to perform these steps before opening the issue)

- [x] I have searched for a similar issue in this repository and did not find one.
- [x] I am using an official build obtained from [releases](https://github.com/shadps4-emu/shadPS4/releases) or updated one of those builds using its in-app updater.
- [x] I have re-dumped the game and performed a clean install without mods and the issue is still present.
- [x] I have disabled all patches and cheats and the issue is still present.
- [x] I have all the required [system modules](https://github.com/shadps4-emu/shadps4-game-compatibility?tab=readme-ov-file#informations) installed.

### Describe the Bug

Trico 1.00-1.03 tested: 
Good performance, goes to 60FPS using vblank 2
Sound relies on SONY extensions/completely mute unless sys_modules are present
Can't climb Trico (!), the spear that should be pulled out is invisible, Trico may not eat barrels (!)
The AI is alive and runs stable enough to not crash, not to mention being fast and not using much CPU, errors related to skipped instructions and models that failed to load was observed and will be posted here. 

Common types of error:

[Core] <Error> stubs.cpp:42 CommonStub: Stub: getpid (nid: HoLVWNanBBc) called, returning zero to 0x94fffc99e
[Core] <Error> stubs.cpp:42 CommonStub: Stub: sceKernelGetProcessType (nid: +g+UP8Pyfmo) called, returning zero to 0x94fffc9a5
[Lib.SysModule] <Error> sysmodule.cpp:60 sceSysmoduleLoadModule: (DUMMY) called module = ORBIS_SYSMODULE_NGS2
[Core] <Error> stubs.cpp:42 CommonStub: Stub: scePthreadSetaffinity (nid: bt3CTBKmGyI) called, returning zero to 0x9009a5b77
[Render.Vulkan] <Error> tile_manager.cpp:220 TryDetile: Unsupported tiled image: R16Sfloat (Texture_Volume)

[Tty] <Info> logger.cpp:62 log_flush: [stdout] CreateBlob: Error. Cannot open file data_trico/ps4_shader_cache/material/GBufferTemplate_DITHER_CLOSE_OBJECT_vs_1977527c_m00000009_90000000_ex00000000.sb.
data_trico/ps4_shader_cache/material/Condor_HornSSS_ps_587672c3_m00000000_90000080_ex00000000.sb.
[Tty] <Info> logger.cpp:62 log_flush: [stdout] CreateBlob: Error. Cannot open file data_trico/ps4_shader_cache/material/GBufferTemplate_MULTIPLY_BLEND_LAYER_ALPHA_vs_e5c75d40_m80202c1f_90000010_ex00000000.sb.
[Tty] <Info> logger.cpp:62 log_flush: [stdout] CreateBlob: Error. Cannot open file data_trico/ps4_shader_cache/material/GBufferTemplate_MULTIPLY_BLEND_LAYER_ALPHA_ps_e5c75d40_m80202c1f_90000010_ex00000000.sb.
[Tty] <Info> logger.cpp:62 log_flush: [stdout] CreateBlob: Error. Cannot open file data_trico/ps4_shader_cache/material/GBufferTemplate_vs_00000000_m0020000e_90000010_ex00000000.sb.
[Tty] <Info> logger.cpp:62 log_flush: [stdout] CreateBlob: Error. Cannot open file 
[Tty] <Info> logger.cpp:62 log_flush: [stdout] CreateBlob: Error. Cannot open file data_trico/ps4_shader_cache/material/BoyCloth3_Forward_BACKLIGHT_SHADOW_ps_cc7f996b_m00400029_90000080_ex00000000.sb.

<img width="1920" alt="Image" src="https://github.com/user-attachments/assets/23a340ef-25c8-449a-9b0d-82204b4a3133" />

<img width="1920" alt="Image" src="https://github.com/user-attachments/assets/056fba2d-7a88-41db-883b-51bffd4c946f" />

<img width="1920" alt="Image" src="https://github.com/user-attachments/assets/520e0658-2b9c-458d-bb2c-a05c5d6a7250" />

### Reproduction Steps

Launch The Last Guardian on ShadPS4/Try climbing, not able to. There is suspicion about Trico not being able to consume barrels.

### Specify OS Version

Windows 11

### CPU

i7-11370H

### GPU

RTX 3060

### Amount of RAM in GB

40

### Amount of VRAM in GB

6

### Log File

[shad_log.txt](https://github.com/user-attachments/files/19948361/shad_log.txt)

**Comment by kalaposfos13** [comment]
Fixed in the latest main.

**Comment by NerosTie** [comment]
It looks like the issue is still here. No spare and Trico doesn't eat the barrel. Tested with the appimage (nightly updates) and `shadps4-git` from AUR (freshly recompiled)

**Comment by DosDokTor** [comment]
Closed as this was fixed.

**Comment by kalaposfos13** [comment]
@NerosTie did you use readbacks and readbackLinearImages? Those experimental options are needed for the game to function properly

**Comment by NerosTie** [comment]
@kalaposfos13 no it was unchecked, I didn't know, now it works very well, thanks!
