### ISSUE TITLE
[macOS] Regression: Several previously working games broken after PR 638 (Add patches for F16C instructions)

### ISSUE THREAD

**Issue by shinra-electric** [shadps4-emu/shadPS4#667]
The following games that were working prior to #638 now crash at launch: 

- CUSA07010 Sonic Mania
- CUSA09415 Undertale
- CUSA11253 Dead Cells

Here are the terminal output and crash log for Sonic. 
[Sonic Crash Report.txt](https://github.com/user-attachments/files/16815985/Sonic.Crash.Report.txt)
[Sonic Terminal Output.txt](https://github.com/user-attachments/files/16815986/Sonic.Terminal.Output.txt)

If you require the logs for the others, let me know.

**Comment by georgemoralis** [comment]
macOS i assume

**Comment by shinra-electric** [comment]
Yep, I mentioned macOS in the title

**Comment by georgemoralis** [comment]
Ah sorry ,@squidbus can look at it

**Comment by shinra-electric** [comment]
They are booting again now, but Dead Cells is crashing after a few seconds of loading into the first level with a Rosetta error: 

```
rosetta error: unexpectedly need to EmulateForward on a synchronous exception x86_rip=0x38670545502 arm_pc=0x481054070892 num_insts=3 inst_index=2 x86 instruction bytes: 0x5083236904201223365 0x11330223254244112
 [1]    1234 abort      ./shadps4
```

**Comment by squidbus** [comment]
Your remaining issue is likely fixed by https://github.com/shadps4-emu/shadPS4/pull/685

**Comment by shinra-electric** [comment]
I tried out that build, but I'm still getting the same error in Dead Cells: 
```
rosetta error: unexpectedly need to EmulateForward on a synchronous exception x86_rip=0x38670545502 arm_pc=0x481054039580 num_insts=3 inst_index=2 x86 instruction bytes: 0x5083236904201223365 0x11330223254244112
```

Edit: I'm getting it in RDR as well
```
rosetta error: unexpectedly need to EmulateForward on a synchronous exception x86_rip=0x38676423265 arm_pc=0x481055062164 num_insts=3 inst_index=2 x86 instruction bytes: 0x5083236904201223365 0x2904972702727768848
```
